* Xiana-blade
** Using REACT components with Clojurescript, Tailwindcss UI and babel
#+begin_quote
This is a WIP! So all suggestions are welcome!
#+end_quote

#+begin_quote
The future goal is to have a *frontend framework* for
Xiana. Supposed to be like a *plugin*

For now it is a *template*, more or less
#+end_quote

** shadow-cljs

*** shadow-cljs.edn
#+begin_quote
You must change this file for your need.
#+end_quote

The important thing here the *src/js* directory this directory is where all
jsx will be compiled to js files.

On the file /*package.json*/ you can change the script to run *babeljs* to
point others directories.

*** babel
To use the components you need to compile the jsx files to js for use with
shadow-cljs. For this we use *babel*

#+begin_src shell
npx babel src/jsx/ --out-dir src/js/ --plugins=@babel/plugin-transform-react-jsx
#+end_src

The npm script `npm run babel` will run a watcher for babel on *src/jsx* directory

#+begin_quote
The important thing here is the output generated by babel

You need add the output directory to the class path so clojurescript can use
the generated js files.
#+end_quote

#+begin_quote
JSX files need not to be on class path
#+end_quote
